### ISSUE TITLE
edb <- ah[[id]], the specified id does not exist.

### ISSUE THREAD

**Issue by JZHT-jiangzhou** [gambalab/gficf#2]
In the process of updating the ensemble database, using the **filterCells** function results in  error:  edb <- ah[[id]], the specified id does not exist.

**Comment by gambalab** [comment]
Annotation hub seems to have problem with last version of dbplyr.
Please try do downgrade it and let me know if the problem is solved. Run the following command to downgrade dblyr.

`devtools::install_version("dbplyr", version = "2.3.4")`

**Comment by gambalab** [comment]
closed due to inactivity
