### ISSUE TITLE
NMF from Current RcppML github version nor CRAN version works without fixes

### ISSUE THREAD

**Issue by adam-cornwell** [gambalab/gficf#3]
Hi, I just started to try this package. It seems that the current NMF function in RcppML is not working, even when I call it directly with either sparse or dense matrices, I always get "Error: Not compatible with requested type: [type=S4; target=double]". Reinstalling the CRAN version of RcppML and sourcing the changes to pathwayAnalisys.R in #1 seems to work still.

**Comment by gambalab** [comment]
Hi, RcppML from CRAN is not supported, so please try to first remove the CRAN version and then install the github version of RcppML. You can do it with the following lines of code

`if("RcppML" %in% rownames(installed.packages())) {remove.packages("RcppML")}
devtools::install_github("zdebruine/RcppML")`

**Comment by gambalab** [comment]
closed due to inactivity
